Handle forking with connection pools more safely
psycopg/psycopg2 pull request #1205
Opened 2020-12-05 02:44 UTC by jmo-qap

Per https://www.psycopg.org/docs/usage.html#thread-and-process-safety reminds you that you shouldn't use libpq connections made in the parent in a fork. However, sometimes one doesn't control the forking and then one spends a lot of time debugging ... :-| This PR makes a connection pool to help catch a situation where a pre-fork connection pool is used post-fork.

This is a Request for Comment and the limitation is that it is only for connection pools and doesn't handle the case where you've already acquired a connection from the pool pre-fork. I think there are other ways to detect this event but figured this was a start.

2020-12-05 13:57 UTC, dvarrazzo requested changes

2020-12-05 13:57 UTC, dvarrazzo commented on lib/pool.py
> +            super().__init__(*self.args, **self.kwargs)
It's not good to just call `__init__` on a class already initialised. I think if you detect this state you should empty the pool: you could add a protected `_flush_pool()` method on the base class to encapsulate it.

2020-12-05 13:57 UTC, dvarrazzo commented on lib/pool.py
> +class MultiProcessThreadedConnectionPool(ThreadedConnectionPool):
Nobody would use a specific subclass if they haven't already gone through some painful debug process as you say. So maybe this should be a change to the base class, not the addition of a new class.

2020-12-05 13:57 UTC, dvarrazzo commented on lib/pool.py
> +            raise Exception("Returned a connection to the pool that was acquired pre-fork. Don't use pre-fork connections post-fork.")
This should probably be a `ProgrammingError`

2020-12-05 14:03 UTC, dvarrazzo commented
I wonder if an anti-fork protection shouldn't be baked into the connection itself. There is already something partial: forking is detected on delete, see #829, so the connection, internally, has the pid it was created on. If we expose that to python, would you be able to do more robust checking?

2021-05-20 14:32 UTC, dvarrazzo commented
Closing as this is a connection problem, not a pool problem.

2021-05-20 14:32 UTC, closed without merging

2021-05-20 16:41 UTC, jmo-qap commented
👍  Will circle back on this when I get a chance to check on connection status. I think a connection-based approach would just check if the init pid is different than the current PID and raise an error. Wouldn't want to create a new connection since that would potentially introduce confusing semantics about previous connection state.